### ISSUE TITLE
Support for Basket Margin

### ISSUE THREAD

**Issue by anilsaxena** [zerodha/pykiteconnect#115]
Would be good to have support for Basket Margin like https://kite.trade/docs/connect/v3/margins/#basket-margins

**Comment by ranjanrak** [comment]
@anilsaxena 
Yeah, we will be adding this soon on all our official libs.

**Comment by mgnanaprakash11** [comment]
Hello,
         When can we expect the addition?  I too Need this Feature.

**Comment by ranjanrak** [comment]
@mgnanaprakash11 
We have already released a new version with a [basket order margin update](https://github.com/zerodha/pykiteconnect/pull/118). You can upgrade to the latest version using 
`pip install kiteconnect --upgrade`

**Comment by mgnanaprakash11** [comment]
When can we expect for node js library?

**Comment by ranjanrak** [comment]
We have added this [here](https://github.com/zerodha/kiteconnectjs/pull/49).

**Comment by bibinvargheset** [comment]
Where can we find the documentation for python?

**Comment by bibinvargheset** [comment]
How can we Execute basket order after getting margins ?

**Comment by ranjanrak** [comment]
> How can we Execute basket order after getting margins ?

You need to prepare a list of orders at your end(in same order as requested while fetching basket margin) and then loop in to place orders on them.
