### ISSUE TITLE
EXCHANGE_MCX is set to "BCD"

### ISSUE THREAD

**Issue by asif-ansari** [zerodha/pykiteconnect#139]
https://github.com/zerodha/pykiteconnect/blob/d5b8ae4c5a33d7e97044d2cf50bdf5382efdd3b7/kiteconnect/connect.py#L77
https://github.com/zerodha/pykiteconnect/blob/d5b8ae4c5a33d7e97044d2cf50bdf5382efdd3b7/kiteconnect/connect.py#L78

Both "BCD" and "MCX" assigned to EXCHANGE_MCX

**Comment by ranjanrak** [comment]
Hi @asif-ansari 
Thank you for pointing it out. It's [updated](https://github.com/zerodha/pykiteconnect/blob/master/kiteconnect/connect.py#L78).
