### ISSUE TITLE
Add support for new ticker mode. QuoteWithTopOffer

### ISSUE THREAD

**Issue by sivamgr** [zerodha/pykiteconnect#142]
Ticker-Quote Mode is without Marketdepth and takes 64 bytes on wire
Ticker-Full Mode is with Marketdepth and takes 184 bytes on wire

Please add support for new ticker mode. QuoteWithTopOffer. In this mode, rather than 5 levels of depth, 1 level of depth shall be provided.

Ticker-QuoteWithTopOffer shall provide Best Bid, Besk Ask along with the Quote data. This only needs 20-24 bytes inaddition to Quote mode. 84 bytes(with no padding) - 88 bytes (with padding)

With this feature available for usecases needing only the top bid/asks, application need not to choose subscribing full-depths and help with reducing the network-streaming traffic by 50%

Also posted a similar request with go implementation, https://github.com/zerodha/gokiteconnect/issues/76

**Comment by rhnvrm** [comment]
Hi

This mode does not exist at the moment, as you can see in the [kite-trade docs](https://kite.trade/docs/connect/v3/websocket/).

Since this is a feature request for kite-trade, this would be more suited as post at https://kite.trade/forum/ to request as a feature.
