### ISSUE TITLE
Authorization Code

### ISSUE THREAD

**Issue by shakefrauf** [zerodha/pykiteconnect#143]
Hi Everyone
I am sure you all are aware that in order to execute sale of holding from zerodha demat one has to enter the authorization code and then a pin is sent on mobile phone by CDSL which in turn has to be entered. But while executing the sale transaction via algo there is no provision to enter the auth code
Can anyone tell me how to enter the auth code for a sale transaction via algo

**Comment by vijaykz** [comment]
You may have to execute a PoA in favor of Zerodha.  Contact support.  You can also verify `demat_consent` from session data as follows:

```
data = generate_session(request_token, api_secret = api_secret)
data = { ... 'meta': {'demat_consent': 'physical'}}
```

If `demat_conset` is physical, you won't need a CDSL pin.

**Comment by shakefrauf** [comment]
> You may have to execute a PoA in the favor of Zerodha. Contact support. You can also verify `demat_consent` from session data as follows:
> 
> ```
> data = generate_session(request_token, api_secret = api_secret)
> data = { ... 'meta': {'demat_consent': 'physical'}}
> ```
> 
> If `demat_conset` is physical, you won't need a CDSL pin.

Hi Vijaykz
I really appreciate your reply.
I have understood what you have said. However i am very new to python and algo trading but i have an experience in trading. So i may take considerable time to pick the python language. Guidance from you and others will help me a lot to learn
