### ISSUE TITLE
Can the kite API be made faster?

### ISSUE THREAD

**Issue by tkanhe** [zerodha/pykiteconnect#146]
The following images show the comparison between pykiteconnect and Kiteconnect REST-API for 15000 F&O instruments.

Current python client:

![Capture1](https://user-images.githubusercontent.com/25158227/155281766-0036e4d8-2f12-4c6f-8c51-53ff7bdf5df4.PNG)

Creating requests session object:

![Capture2](https://user-images.githubusercontent.com/25158227/155281796-332087de-db99-4e59-95b4-48e53d7d19f8.PNG)

Asynchronous execution:

![Capture3](https://user-images.githubusercontent.com/25158227/155281814-26b6d3e5-bea8-48ed-b05e-f01b5af7eddf.PNG)

Let me know if it can be improved further.

**Comment by knadh** [comment]
hm, in your first example, you're making 15,000 HTTP requests, one for each instrument?

**Comment by tkanhe** [comment]
@knadh no, list (var_name:"opl") of about 490 instuments as there is limit of 500.

**Comment by ranjanrak** [comment]
Create requests session by default for connection reuse is available in a [new release v4.2.0](https://github.com/zerodha/pykiteconnect/releases/tag/v4.2.0).

**Comment by vijaykz** [comment]
Does using the _pool_ make API requests fasters?

**Comment by vividvilla** [comment]
@vijaykz Ideally yes since there is no overhead to create new connections, do note that if you face any issues then set configure pool config - https://github.com/zerodha/pykiteconnect/blob/master/kiteconnect/connect.py#L194
