### ISSUE TITLE
unable to procced with  buy  or sell banknifty 

### ISSUE THREAD

**Issue by akjoshi009** [zerodha/pykiteconnect#154]
order_id = kite.place_order(tradingsymbol="BANKNIFTY7JUL33700PE",
                                exchange=kite.EXCHANGE_NFO,
                                transaction_type=kite.TRANSACTION_TYPE_BUY,
                                quantity=25,
                                variety=kite.VARIETY_REGULAR,
                                order_type=kite.ORDER_TYPE_MARKET,
                                product=kite.PRODUCT_MIS,
                                validity=kite.VALIDITY_DAY)

after executing this error The instrument you are placing an order for has either expired or does not exist

**Comment by ranjanrak** [comment]
You are using the wrong trading symbol for the weekly banknifty contract, it should be `BANKNIFTY2270733700PE`. Go through the kite connect dev forum [FAQs here](https://kite.trade/forum/discussion/4732/frequently-asked-questions-faqs#instrument-token) to know more about this.
