### ISSUE TITLE
Kiteconnect: Too many requests

### ISSUE THREAD

**Issue by varunjain3** [zerodha/pykiteconnect#165]
Today Morning I experienced this issue. This issue has never had happened in the past 2 years. I know that this occurs when I exceed the API rate limit. But, I don't think so it's the rate limit that is causing this issue. My app was working smoothly with almost the same number of API calls everyday. Suddenly I am getting the same message and I am not able to receive any more data from the API until I reboot my server. 

I have 2 instances of the api running through the same server. By 2 instances I mean 2 different accounts of the API with 2 different Access token. I also observed that as soon as one of the account broke down, the other one also did. So I felt that somehow my server IP is not letting passed through. Was their a recent change in the api? What can be the reason for this?

**Comment by KamalChhirang** [comment]
https://kite.trade/forum/discussion/11971/api-rate-limits

**Comment by ranjanrak** [comment]
[This kiteconnect forum thread](https://kite.trade/forum/discussion/11971/api-rate-limits) provides detailed information about API rate limits and throttling periods. If you have any additional questions or concerns, you can continue the discussion in the same forum thread. We will be closing this issue now.
