### ISSUE TITLE
example for option trading code?

### ISSUE THREAD

**Issue by assistuelectronics** [zerodha/pykiteconnect#173]
Hi,

I am looking for easy integration for option trading where I can get live data of the option and then place the order?

**Comment by ranjanrak** [comment]
We can use WebSocket streaming. For detailed information and implementation, refer to the [KiteConnect API documentation](https://kite.trade/docs/connect/v3/websocket/). If you have any additional questions, you can write on [the kiteconnect forum](https://kite.trade/forum/).
