### ISSUE TITLE
kite.ltp  and kite.quate  not working

### ISSUE THREAD

**Issue by sandipawar** [zerodha/pykiteconnect#194]
kite.ltp  and kite.quate  not working   any solution ??

**Comment by vzanvar-wdc** [comment]
Can you post a code snippet?

**Comment by sandipawar** [comment]
kite = KiteApp(enctoken=enctoken)

print("Net Balance : ", kite.margins()["equity"]['net'])   ' >> Not working    
kite.ltp("NSE:NIFTY 50")["NSE:NIFTY 50"]["last_price"]   ' >> Not working
kite.quote("NSE:NIFTY 50")["NSE:NIFTY 50"]['ohlc']['close']  ' >> Not working

**Comment by vzanvar-wdc** [comment]
Have you generated the access token? i.e, kite..generate_session() should be called.

[This example](https://github.com/zerodha/pykiteconnect/blob/master/examples/simple.py
) would work.

**Comment by sandipawar** [comment]
sorry i got it problem,  i think i used  private python library like -  from kiteext import KiteExt

**Comment by sandipawar** [comment]
thank you i understand
