### ISSUE TITLE
Cant install Kiteconnect in python 2.7.

### ISSUE THREAD

**Issue by muthuselvamlms** [zerodha/pykiteconnect#53]
sudo pip install --upgrade kiteconnect
Password:
The directory '/Users/User/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has beendisabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/User/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has beendisabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting kiteconnect
  Downloading https://files.pythonhosted.org/packages/5a/dc/482cb13486946889b6a26abeb4036f5b8af19978251cc61f0ee45de4d833/kiteconnect-3.7.6.tar.gz
Requirement already satisfied, skipping upgrade: requests>=2.18.4 in /Users/User/Library/Python/2.7/lib/python/site-packages (from kiteconnect) (2.20.1)
Requirement already satisfied, skipping upgrade: six>=1.11.0 in /Library/Python/2.7/site-packages (from kiteconnect) (1.11.0)
Requirement already satisfied, skipping upgrade: pyOpenSSL>=17.5.0 in /Users/User/Library/Python/2.7/lib/python/site-packages (fromkiteconnect) (18.0.0)
Requirement already satisfied, skipping upgrade: enum34>=1.1.6 in /Library/Python/2.7/site-packages (from kiteconnect) (1.1.6)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /Library/Python/2.7/site-packages (from kiteconnect) (2.7.0)
Requirement already satisfied, skipping upgrade: autobahn[twisted]>=17.10.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (from kiteconnect) (18.9.2)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /Users/User/Library/Python/2.7/lib/python/site-packages (from requests>=2.18.4->kiteconnect) (2.7)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /Library/Python/2.7/site-packages (from requests>=2.18.4->kiteconnect) (1.22)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests>=2.18.4->kiteconnect) (2018.8.24)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /Users/User/Library/Python/2.7/lib/python/site-packages (from requests>=2.18.4->kiteconnect) (3.0.4)
Requirement already satisfied, skipping upgrade: cryptography>=2.2.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (from pyOpenSSL>=17.5.0->kiteconnect) (2.3.1)
Requirement already satisfied, skipping upgrade: txaio>=18.8.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (from autobahn[twisted]>=17.10.1->kiteconnect) (18.8.1)
Requirement already satisfied, skipping upgrade: zope.interface>=3.6.0; extra == "twisted" in /Users/User/Library/Python/2.7/lib/python/site-packages (from autobahn[twisted]>=17.10.1->kiteconnect) (4.5.0)
Requirement already satisfied, skipping upgrade: Twisted>=12.1.0; extra == "twisted" in /Users/User/Library/Python/2.7/lib/python/site-packages (from autobahn[twisted]>=17.10.1->kiteconnect) (18.7.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.7 in /Users/User/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.2.1->pyOpenSSL>=17.5.0->kiteconnect) (1.11.5)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /Users/User/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.2.1->pyOpenSSL>=17.5.0->kiteconnect) (0.24.0)
Requirement already satisfied, skipping upgrade: ipaddress; python_version < "3" in /Users/User/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.2.1->pyOpenSSL>=17.5.0->kiteconnect) (1.0.22)
Requirement already satisfied, skipping upgrade: setuptools in /Library/Python/2.7/site-packages (from zope.interface>=3.6.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (38.5.2)
Requirement already satisfied, skipping upgrade: constantly>=15.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (from Twisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (15.1.0)
Requirement already satisfied, skipping upgrade: incremental>=16.10.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (from Twisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (17.5.0)
Requirement already satisfied, skipping upgrade: Automat>=0.3.0 in /Users/User/Library/Python/2.7/lib/python/site-packages (from Twisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (0.7.0)
Requirement already satisfied, skipping upgrade: hyperlink>=17.1.1 in /Users/User/Library/Python/2.7/lib/python/site-packages (fromTwisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (18.0.0)
Requirement already satisfied, skipping upgrade: PyHamcrest>=1.9.0 in /Users/User/Library/Python/2.7/lib/python/site-packages (fromTwisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (1.9.0)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /Users/User/Library/Python/2.7/lib/python/site-packages (from Twisted>=12.1.0; extra == "twisted"->autobahn[twisted]>=17.10.1->kiteconnect) (18.2.0)
Requirement already satisfied, skipping upgrade: pycparser in /Users/User/Library/Python/2.7/lib/python/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyOpenSSL>=17.5.0->kiteconnect) (2.19)
Installing collected packages: kiteconnect
  Found existing installation: kiteconnect 3.7.4
    Uninstalling kiteconnect-3.7.4:
      Successfully uninstalled kiteconnect-3.7.4
  Running setup.py install for kiteconnect ... done
  Could not find .egg-info directory in install record for kiteconnect from https://files.pythonhosted.org/packages/5a/dc/482cb13486946889b6a26abeb4036f5b8af19978251cc61f0ee45de4d833/kiteconnect-3.7.6.tar.gz#sha256=fdd55316bd66a6772e6ec71cea1ace2aa779b31b4e8ae5edff83c017aa94bb81 in /Users/User/Library/Python/2.7/lib/python/site-packages/kiteconnect-3.7.4-py2.7.egg
Successfully installed kiteconnect
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/cli/base_command.py", line 184, in main
    timeout=min(5, options.timeout)
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/cli/base_command.py", line 79, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/download.py", line 337, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/download.py", line 126, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_internal/utils/misc.py", line 836, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 562, in __init__
    self.add_entry(entry)
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 618, in add_entry
    for dist in find_distributions(entry, True):
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1883, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1402, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1757, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1634, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/Users/User/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1591, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/Users/User/Library/Python/2.7/lib/python/site-packages/kiteconnect-3.7.4-py2.7.egg'

**Comment by muthuselvamlms** [comment]
getting Could not find .egg-info directory in install record for kiteconnect from while installing. Any Help Thanks in advance

**Comment by sdabhi23** [comment]
Facing the same issue on python 3.6

**Comment by vividvilla** [comment]
This should have been fixed on `kiteconnect>=3.9.0`. You can try doing 
```
pip install --upgrade kiteconnect
```

**Comment by vividvilla** [comment]
Also we are planning to deprecate support for Python 2.7 so would advice you to migrate to Python 3.6+
