### ISSUE TITLE
AttributeError: 'KiteTicker' object has no attribute 'ws'

### ISSUE THREAD

**Issue by vividvilla** [zerodha/pykiteconnect#72]
https://kite.trade/forum/discussion/7279/possible-bug-in-kiteticker-is-connected#latest

**Comment by shreyass-ranganatha** [comment]
Anyone working on this? I could take this up, if it's still up for grabs

**Comment by ranjanrak** [comment]
It was already fixed through [this commit](https://github.com/zerodha/pykiteconnect/pull/157). Closing this issue.
