### ISSUE TITLE
How to get historical data of indices?

### ISSUE THREAD

**Issue by hemangjoshi37a** [zerodha/pykiteconnect#78]
Dear sir,

There is absolute no documentation on how to read indices like NIFTY from historical_data() function or by any other way.

Please help me.
Thank you in advance sir.

**Comment by rahulmr** [comment]
Not sure about the documentation but I think below code might help you.

```python
...
...
import pandas as pd
from datetime import datetime as dt
from datetime import timedelta as td
...
...
... 
# do all kite object creation steps
sbin_token = kite.ltp("NSE:SBIN")['NSE:SBIN']['instrument_token']
df = pd.DataFrame(kite.historical_data(
    sbin_token, dt.today() - td(days=7), dt.today(), '15minute'))
print(df)

nf_token = kite.ltp("NSE:NIFTY 50")['NSE:NIFTY 50']['instrument_token']
df = pd.DataFrame(kite.historical_data(
    nf_token, dt.today() - td(days=7), dt.today(), '15minute'))
print(df)
bnf_token = kite.ltp("NSE:NIFTY BANK")['NSE:NIFTY BANK']['instrument_token']
df = pd.DataFrame(kite.historical_data(
    bnf_token, dt.today() - td(days=7), dt.today(), '15minute'))
print(df)
```

**Comment by avisharmaanubhav** [comment]
nifty 50 has instrument token 256265 so specifically mentioning the code for it or you can change the instrument token and get historical data for other indices as well.

historical_days_nifty50 = kite.historical_data(256265, (datetime.datetime.now()- datetime.timedelta(days=9)).strftime(
        "%Y-%m-%d %H:%M:%S"), (datetime.datetime.now()).strftime("%Y-%m-%d %H:%M:%S"), "day", continuous=False,
                                              oi=False)

**Comment by ranjanrak** [comment]
The [response structure](https://kite.trade/docs/connect/v3/historical/#response-structure) section of all API calls explains the fields.

**Comment by hemangjoshi37a** [comment]
> Not sure about the documentation but I think below code might help you.
> 
> ```python
> ...
> ...
> import pandas as pd
> from datetime import datetime as dt
> from datetime import timedelta as td
> ...
> ...
> ... 
> # do all kite object creation steps
> sbin_token = kite.ltp("NSE:SBIN")['NSE:SBIN']['instrument_token']
> df = pd.DataFrame(kite.historical_data(
>     sbin_token, dt.today() - td(days=7), dt.today(), '15minute'))
> print(df)
> 
> nf_token = kite.ltp("NSE:NIFTY 50")['NSE:NIFTY 50']['instrument_token']
> df = pd.DataFrame(kite.historical_data(
>     nf_token, dt.today() - td(days=7), dt.today(), '15minute'))
> print(df)
> bnf_token = kite.ltp("NSE:NIFTY BANK")['NSE:NIFTY BANK']['instrument_token']
> df = pd.DataFrame(kite.historical_data(
>     bnf_token, dt.today() - td(days=7), dt.today(), '15minute'))
> print(df)
> ```

Thanks. Your solution works.
https://hjlabs.in
