### ISSUE TITLE
Reactor Not Restartable Error

### ISSUE THREAD

**Issue by YogeshSingla** [zerodha/pykiteconnect#80]
On closing a KiteTicker object through the jupyter notebook interrupt, rerunning the cell gives a 
Reactor Not Restartable error.

**Comment by arul67800** [comment]
openin in a new console solves this for me

**Comment by hemangjoshi37a** [comment]
Have you fond any solution for this error? I am having same issue.

**Comment by ranjanrak** [comment]
> ReactorNotRestartable

This error is thrown by [Twisted](https://github.com/twisted/twisted/blob/1d439dd1d9c7d302641550a925705d479ea5457f/src/twisted/internet/error.py#L384), when you are trying to re-run a reactor that was stopped. You can not use the same process to re-run the reactor, once it's stopped by `reactor.stop()` event. This event is used in the [on_close](https://github.com/zerodha/pykiteconnect/blob/master/kiteconnect/ticker.py#L559) method in the kiteconnect ticker.
