### ISSUE TITLE
Getting error while logging through Flask App

### ISSUE THREAD

**Issue by prakhar-goel** [zerodha/pykiteconnect#81]
https://github.com/zerodhatech/pykiteconnect/blob/f71087f35ff27178b99646790a3d8850452e0f02/examples/flask_app.py#L43

I am following the flask app. At the time of login, I get the following error message:
`{"status":"error","message":"Route not found","data":null,"error_type":"GeneralException"}`

Looks like the login URL is incorrect.

**Comment by suraj9321** [comment]
login_url = "https://kite.trade/connect/login?api_key={api_key}".format(api_key=kite_api_key)

update this with this url. Working fine after changing to this

**Comment by ranjanrak** [comment]
This is already updated in the [latest release](https://github.com/zerodha/pykiteconnect/blob/master/examples/flask_app.py#L43).
