### ISSUE TITLE
Every two minute i got this error - Connection error: 1006 - connection was closed uncleanly (None)

### ISSUE THREAD

**Issue by karthickbala123** [zerodha/pykiteconnect#88]
I read previous discussions about this error but am not resolve this issue
am also not using any computation inside on_ticks(). kindly help me

```
susbcription_list = [int(x) for x in trd_portfolio]
def getticks(ticks):
for tick in ticks:
ticks_token = tick['instrument_token']
push_tick_values_to_trd_portfolio(tick, ticks_token)

push_value_to_excel()
def on_ticks(ws, ticks):
# Todo: "On_ticks"
getticks(ticks)

def on_connect(ws, response):
ws.subscribe(susbcription_list)
ws.set_mode(ws.MODE_FULL, susbcription_list)


# Assign the callbacks.
kws.on_ticks = on_ticks
kws.on_connect = on_connect


kws.connect(threaded=True)

count = 0
while True:
count += 1
if count % 2 == 0:
if kws.is_connected():
kws.set_mode(kws.MODE_FULL, susbcription_list)
else:
if kws.is_connected():
kws.set_mode(kws.MODE_FULL, susbcription_list)

time.sleep(5)
```
![image](https://user-images.githubusercontent.com/63300069/90264501-d20c1f00-de6e-11ea-8c3e-19598818cd3d.png)

**Comment by vijaykz** [comment]
```
push_tick_values_to_trd_portfolio(tick, ticks_token)
push_value_to_excel()
```
By looks, these seem to be time consuming operations.  Try doing only in-memory operations in `on_ticks()` and offload other functionalities to a separate thread.

**Comment by karthickbala123** [comment]
Thank you for your reply @vijaykz can you send some exapmle code for  memory operations bcoz am basic python user only. kindly help me

**Comment by vijaykz** [comment]
Refer to [this example](https://github.com/vividvilla/kite-connect-python-example).  This shows how to fetch & store ticks.  Instead of database, you can simply maintain candles in list of list, for example.

**Comment by sachin2404** [comment]
Hi Vijaykz , In your [example](https://github.com/zerodha/kite-connect-python-example), you said you are sending ticks in celery taske queue where ticks are inserted into DB. But what if I want to do operation on latest ticks not on previous ticks. I want to compute on instant basis while getting ticks.

**Comment by vijaykz** [comment]
I do not have a need to save in DB.  I create candlesticks in a list of list like this:

`ticks = [ [Date, O, H, L, C, V],
[Date, O, H, L, C, V],
....
[Date, O, H, L, C, V] ] `

In order to perform operations on the latest bar, you can fetch it just by using `ticks[-1]`
