### ISSUE TITLE
threaded ticker comment says 'nothing will run after this', but it does!

### ISSUE THREAD

**Issue by rushiagr** [zerodha/pykiteconnect#96]
file: examples/threaded_ticker.py

**Comment by vividvilla** [comment]
Comment was wrong, will be fixed in next version.

**Comment by ranjanrak** [comment]
Setting `threaded=True` creates a new daemon thread and an infinite while loop is used in this example to keep the main thread alive/blocked. [Multi-line comments here](https://github.com/zerodha/pykiteconnect/blob/master/examples/threaded_ticker.py#L7-L11) explain the same. You can use anything from static sleep to threading wait event loop to block the main thread as per your requirement.
